### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by InfTkm** [OpenLiberty/guide-maven-multimodules#103]
Takes about 30 minutes to finish the guide. The doc is well-written.  
Minor things:
- In the section, What you’ll learn, 2nd paragraph, may want to change `a multimodules application` to `a multi-module application`.
- For the maven option, `-pl`, maybe the verbose choice `--projects` is clearer for beginners to understand the meaning.

**Comment by gkwan-ibm** [comment]
for the second point, may update the statement at the "Try what you’ll build" subsection instead of the command. At the first occurrence of 
> ...using the `-pl ear` flag...

update to
> ...using the `-pl ear` or `--projects ear` flag...

**Comment by ryan-storey** [comment]
All added, thank you both.
