### ISSUE TITLE
Re-review for multimudules guide

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guide-maven-multimodules#14]
**What you’ll learn**
- [x] "which consists of **a** web archive..." -> missing "a"
- [x] "Package modules and resources into an EAR file to deploy or distribute the Java EE application to new environments." -> this sentences seems a bit off, it doesn't really flow with the rest of the paragraph
- [x] all in all, this whole paragraph is kind of weird, all you need to explain is 1) what multi modules are 2) how to build them
- [x] "Next, use Maven..." -> this sentence is not in future tense like the previous sentence, but it should be
- [x] "Enter heights in centimeters..." -> same problem as above
- [x] "When the application is running, you can access the unit converter at the following **endpoint**:'?

**Getting started**
- [x] "Add a dependency relationship between two **the** modules."

**Adding dependencies between WAR and JAR modules**
- [x] "To use the Java library in your web module, add a dependency relationship between them." -> perhaps this would be better: "To use a Java library in your web module, you must add a dependency relationship between the two."
- [x] "As you might notice" -> "As you might have noticed"
- [x] "each module has its own pom.xml file because each module is treated as an independent project." -> the "because" part of the sentence should probably be its own sentence; ie. "each module hsa its own pom.xml. This is because..."
- <del>"After you add the dependency, use any functions included in the library in the HeightsBean.java class of the web module." -> this is an awkward sentence, I dont really understand what it wants me to do, but I suspect this was original saying something like "you can use any functions included". I think it needs to be changed back, present tense doesn't work here at all</del>
- <del>is there any way to avoid long package names? ex. "io.openliberty.guides.multimodules.lib.Converter.getFeet(cm);"</del>

**Assembling multiple modules into an EAR file**
- [x] "Use the EAR project to assemble multiple modules into an EAR file." -> "To do this, ..."
- <del>the modelVersion should be already in the template, its simply a model the POM complies with and it will almost always be 4.0.0, otherwise you're making it look like its some kind ear version for your app</del>
- [x] "If you don’t specify the web module, Maven looks for a JAR file" -> convert to future tense "If you don’t specify the web module, then Maven will look for a JAR file"
- <del> perhaps you should briefly explain what the maven-ear-plugin does </del>
- [x] I think the server.xml can be left out and just provided. You're just telling the users to copy paste stuff into it anyway without explaining what any of it does.
- <del>"To build the three modules, run the following commands from the jar directory, war directory, and ear directory in that order. Start with the jar directory, proceed to the war directory, and end with the ear directory." -> basically says the same thing twice </del>

**Starting the application**
- <del>why does the user need to run "cd ../../start/ear"? They should already be in the ear dir from the previous step</del>
- <del>"Once the server is running, you can find the application at the following URL:" -> this should point to a clickable URL</del>
- <del>"start-server" and "stop-server" should also be copyable</del>

**Testing the multi-module application**
- <del>is just "Test" really a good enough name here? Perhaps "EndpointIT"? where "IT" = integration test</del>
- <del>you should just import the Test annotation, using "@org.junit.Test" is kind of awkward</del>
- <del>"For a Maven EAR project..." -> you should include a path to the POM file</del>
- <del>the "testCompile" goal is already in the pom file, no need to add it</del>
- <del>you should mention that the server must be stopped if it wasn't already for "mvn verify" to work</del>
- <del>"The program returns the following output:" -> should be something like "If everything compiled successfully, then you will see the following output:"</del>
- <del>"Lastly, add a parent section to each of the pom.xml files in the child modules, such as the jar, war, and ear projects:" -> remove "such as the" and replace it with something else like "that is intro the jar, war, and ear projects"</del>

**Great work! You’re done!**
- [x] "You **just** built..."

**Comment by TiagoF99** [comment]
in progress

**Comment by TiagoF99** [comment]
> "which consists of a web archive..." -> missing "a"
- I dont think this is necessary as an EAR can have mutliple WAR and JAR files and the sentence already reflects this.
