### ISSUE TITLE
Multipane Issue

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-maven-multimodules#29]
### Checklist for Post-Review
**Through the browser:**
- [x] Read through guide, making sure that the flow of the guide is good
- [x] Click all links to make sure they lead to the correct place
- [x] Make sure hotspots, code_commands and files are correct
- [x] Run Acrolinx

**Comment by justineechen** [comment]
- [ ] In `What you’ll learn`, the link `http://localhost:9080/converter/` should be clickable
- [ ] First instance of `pom.xml` in `Adding dependencies between WAR and JAR modules` should be highlighted 
- [ ] Remove space in `<element/>`
- [ ] In `Testing the multi-module application`, first instance of `Test.java` should be hot spotted 
- [ ] In `Aggregating the entire build`, it says to "Create the pom.xml" but the arrow says "Edit the pom.xml" 
- [ ] Last arrow in `Aggregating the entire build` has the missing < />, did you use Steven's fix ?
- [ ]

**Comment by Rachelwrq** [comment]
#### Building the modules
Noticed the ports are not configured successfully, which could the cause of later problems listed below.

#### Starting the application
Cannot connect to the url `http://localhost:9080/converter/`.

#### Testing the multi-module application
running `mvn verify` at the end yields

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M1:verify (verify-results) on project io.openliberty.guides.multimodules.ear: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/aidan.poleseibm.com/guideRepos/guide-maven-multimodules/start/ear/target/test-reports/it for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

-------------------------------------------------------------------------------
Test set: it.io.openliberty.guides.multimodules.Test
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.062 s <<< FAILURE! - in it.io.openliberty.guides.multimodules.Test
testHeightsPage(it.io.openliberty.guides.multimodules.Test)  Time elapsed: 0.032 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at it.io.openliberty.guides.multimodules.Test.testBufferHelper(Test.java:62)
	at it.io.openliberty.guides.multimodules.Test.testHeightsPage(Test.java:58)

testIndexPage(it.io.openliberty.guides.multimodules.Test)  Time elapsed: 0.001 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at it.io.openliberty.guides.multimodules.Test.testIndexPage(Test.java:48)
```

**Comment by justineechen** [comment]
The above issue is resolved/ could not be replicated. ^
