### ISSUE TITLE
Multipane tabs disappearing

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/guide-maven-multimodules#35]
Tabs disappear from code-pane when opening a new file.

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/openliberty.io/issues/1053

**Comment by steven1046** [comment]
It should be fixed now: https://openliberty.io/guides/maven-multimodules.html

**Comment by justineechen** [comment]
Thank you @steven1046 !
