### ISSUE TITLE
Does this need to be updated to use JUnit 5?

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-maven-multimodules#59]
The test dependency used in the `war` folder is:
```
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.12</version>
    <scope>test</scope>
</dependency>
```

We updated to use JUnit 5, do we need to update this too?

**Comment by gkwan-ibm** [comment]
should remove it instead of updating to junit 5 because no test for war folder

**Comment by MaiHameed** [comment]
Addressed: https://github.com/OpenLiberty/guide-maven-multimodules/pull/60
