### ISSUE TITLE
two missing steps

### ISSUE THREAD

**Issue by ibmfjk** [OpenLiberty/guide-maven-multimodules#6]
1. No step to set basic configuration in start/pom.xml
2. No step to configure parent in start/ear/pom.xml, start/war/pom.xml, start/jar/pom.xml

**Comment by JunyiSun** [comment]
Hi @ibmfjk , thank you for your feedback! However,  I believe the two steps you mentioned are provided in the `Aggregating the entire build` section of this guide, which is the section after the testing section. Please double check that, if you still have any concerns, you are more than welcome to leave the feedback here. 
https://github.com/OpenLiberty/guide-maven-multimodules#aggregating-the-entire-build

**Comment by yeekangc** [comment]
@ibmfjk, can you please elaborate on your concerns especially if you have additional feedback?  Thank you.

**Comment by ibmfjk** [comment]
oh, sorry, I did not see the Aggregating the entire build section, I think we can close this issue.

**Comment by yeekangc** [comment]
Thank you, @ibmfjk.
